version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: golfclub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: golfclub
      MYSQL_USER: golfer
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - golfclubNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "golfer", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: golfclub-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - golfclubNetwork

networks:
  golfclubNetwork:
    driver: bridge

volumes:
  mysql-data: